/**
 * Script:
 *   00_segment_cells_selected_annotations.groovy
 *
 * Purpose:
 *   Segment DAPI-positive nuclei/cells inside selected annotations.
 *
 * Workflow position:
 *   Step 2 — Cell segmentation
 *
 * Input:
 *   - Selected annotation objects
 *   - DAPI image channel
 *
 * Output:
 *   - Cell / detection objects
 *   - Intensity measurements generated by WatershedCellDetection
 *
 * Recommended usage:
 *   First use on selected annotations for parameter tuning before batch analysis.
 *
 * Notes:
 *   Existing child objects inside selected annotations will be cleared.
 *   Visual QC is strongly recommended.
 */

import static qupath.lib.scripting.QP.*

// ================== [参数区：保持不变] ==================
def global_DAPI_min = 0.0
def global_DAPI_max = 134.0
def myThreshold = 20.0

def detectionParams = [
    "detectionImage": "DAPI (C1)",
    "requestedPixelSizeMicrons": 0.5,
    "backgroundRadiusMicrons": 6.0,
    "medianRadiusMicrons": 1.0,
    "sigmaMicrons": 1.0,
    "minAreaMicrons": 5.0,
    "maxAreaMicrons": 400.0,
    "threshold": myThreshold,
    "watershedPostProcess": true,
    "cellExpansionMicrons": 2.5,
    "includeNuclei": true,
    "smoothBoundaries": true,
    "makeMeasurements": true,
    "backgroundByReconstruction": true
]
// =======================================================

// 1. 获取当前图像数据
def imageData = getCurrentImageData()
if (imageData == null) {
    println "错误：没有打开的图像！"
    return
}
def hierarchy = imageData.getHierarchy()

// 2. 获取当前【选中】的 Annotation
// 修正逻辑：仅操作用户在 UI 中选中的区域
def selectedAnnotations = getSelectedObjects().findAll { it.isAnnotation() }

if (selectedAnnotations.isEmpty()) {
    println "⚠️ 错误：未选中任何 Annotation！请先在图像中选中目标区域（如 Normalization Patch）。"
    return
}

println ">>> 开始对选中的 ${selectedAnnotations.size()} 个区域运行细胞核分割..."

// 3. 【核心修复】设置 DAPI 亮度
// 依据: QPEx.setChannelDisplayRange(String channelName, double min, double max)
try {
    // 使用辅助方法避免复杂的类路径调用，且能自动处理通道名匹配
    setChannelDisplayRange("DAPI", global_DAPI_min as double, global_DAPI_max as double)
    println "  [亮度已设置] DAPI 范围: $global_DAPI_min - $global_DAPI_max"
} catch (Exception e) {
    println "  [提示] 亮度设置失败 (可能没找到DAPI通道): " + e.getMessage()
}

// 4. 遍历选中的 Annotation 执行检测
selectedAnnotations.each { patch ->
    println "--- 正在处理区域: ${patch.getName() ?: '未命名'} ---"
    
    // 清理旧子对象
    patch.clearChildObjects() 
    
    // 设置当前 Patch 为活动选区，以便 runPlugin 运行
    hierarchy.getSelectionModel().setSelectedObject(patch)
    
    // 运行检测
    // 依据: WatershedCellDetection 在 v0.5.1 中依然是标准插件
    runPlugin('qupath.imagej.detect.cells.WatershedCellDetection', imageData, detectionParams)
    
    // 【归位逻辑】确保检测到的细胞被正确挂载在选中的 Patch 下
    def orphans = hierarchy.getDetectionObjects().findAll { it.getParent() == null || it.getParent().isRootObject() }
    if (!orphans.isEmpty()) {
        patch.addPathObjects(orphans)
        println "  [归位成功] 已将 ${orphans.size()} 个细胞移至当前 Patch"
    }
}

// 5. 更新界面
fireHierarchyUpdate()
println "\n[任务完成] 分割已结束，请检查界面效果。"